### ISSUE TITLE
add linkedin badge

### ISSUE THREAD

**Issue by Mercotui** [Mercotui/mercotui.github.io#1]
example code `<div class="LI-profile-badge"  data-version="v1" data-size="medium" data-locale="nl_NL" data-type="vertical" data-theme="dark" data-vanity="menno-van-der-graaf-13138490"><a class="LI-simple-link" href='https://nl.linkedin.com/in/menno-van-der-graaf-13138490?trk=profile-badge'>Menno van der Graaf</a></div>`

**Comment by idelsink** [comment]
You can use this for all sort's of icons: http://fontawesome.io/

**Comment by Mercotui** [comment]
thanks for sharing the resource, currently only used googles icon database, but they lack all the brand icons. Will give it a look

**Comment by idelsink** [comment]
If you want to see how you can us it, look at this project: [DNS/index.html](https://github.com/derpicated/dynamic_network_of_speakers/blob/e2407d330a2f83d8a2de33cc9905d783906c7dfc/website/index.html#L62). This project also uses [font awsome](http://fontawesome.io/)

**Comment by Mercotui** [comment]
btw, I did end up using the icons from fontawesome!
👍
